name: dr_mohamed_salah_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3+1
  pusher_channels_flutter: ^2.2.1
  liquid_pull_to_refresh: ^3.0.1
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  localize_and_translate: ^5.1.2
  get_it: ^7.7.0
  dartz: ^0.10.1
  loading_overlay: ^0.3.0
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  oktoast: ^3.4.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  jiffy: ^6.2.1
  lottie: ^3.1.2
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.2.1+2
  regexpattern: ^2.6.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_animate: ^4.5.0
  pin_code_fields: ^8.0.1
  animated_bottom_navigation_bar: ^1.3.3
  dropdown_search: ^5.0.6
  easy_date_timeline: ^1.0.3
  dotted_border: ^2.1.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  rename: ^3.0.2
  flutter_pdfview: ^1.3.2
  file_picker: ^8.0.7
  url_launcher: ^6.3.0
  onesignal_flutter: ^5.1.2
  pdf: ^3.11.1
  open_file: ^3.5.4
  device_info_plus: ^10.1.2
  path_provider: ^2.1.4
  bluetooth_print: ^4.3.0
  printing: ^5.13.1
  widget_zoom: ^0.0.4
  webview_flutter: ^4.8.0
  pretty_dio_logger: ^1.4.0


dependency_overrides:
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  remove_alpha_ios: true
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lang/
    - assets/temp/


  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf